name: Delete abandoned branches

on:
  # Run daily at midnight
  schedule:
    - cron: "*/2 * * * *"

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  cleanup_old_branches:
    runs-on: ubuntu-latest
    name: Delete unused branches
    steps:
      - name: Delete unused branches
        uses: phpdocker-io/github-actions-delete-abandoned-branches@v1
        id: deleted_branches
        with:
          github_token: ${{ github.token }}
          last_commit_age_days: 100
          dry_run: no

      - name: Get output
        run: "echo 'Deleted branches: ${{ steps.deleted_branches.outputs.deleted_branches }}'"
